name: ZAP DAST Scan

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: ZAP Full Scan on Juice Shop

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Pull ZAP Docker Image
        run: docker pull ghcr.io/zaproxy/zaproxy:stable

      - name: Run ZAP Full Scan using Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/zap/wrk \
            ghcr.io/zaproxy/zaproxy:stable zap-full-scan.py \
            -t https://juice-shop.herokuapp.com \
            -r zap_report.html \
            -u https://juice-shop.herokuapp.com \
            -z "-config connection.ssl_cert_validation=false"

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-dast-report
          path: zap_report.html
