name: ZAP DAST Scan

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: ZAP DAST Scan on Juice Shop

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Run ZAP Full Scan
        id: zap
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://juice-shop.herokuapp.com'
          # Remove --insecure, add SSL ignore config in -z if needed
          cmd_options: '-a -z "-config connection.ssl_cert_validation=false"'
          allow_issue_writing: false  # Avoids opening issues automatically

      - name: Upload ZAP Report Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: zap-dast-reports
          path: |
            report_html.html
            report_json.json
            zap.log
