name: ZAP DAST Scan

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: ZAP Full Scan via Docker

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create temp report directory
        run: |
          mkdir -p zap-output
          chmod -R 777 zap-output  # Make sure it's writable by container

      - name: Run ZAP Full Scan using Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/zap-output:/zap/wrk \
            ghcr.io/zaproxy/zaproxy:stable zap-full-scan.py \
            -t https://juice-shop.herokuapp.com \
            -r zap_report.html \
            -J zap_report.json \
            -w zap_report.md \
            -z "-config connection.ssl_cert_validation=false" || true

      - name: Upload ZAP Scan Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-scan-report
          path: |
            zap-output/zap_report.html
            zap-output/zap_report.json
            zap-output/zap_report.md
